services:
  nestjs_api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - NODE_ENV=development
    volumes:
      - ./src:/app/src
    networks:
      - nesttodo
  mysql_db:
    image: mysql
    ports:
      - '3307:3307'
    environment:
      - MYSQL_ROOT_PASSWORD=root_password_123
      - MYSQL_DATABASE=nesttodo_be_dev
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=testuser123
      - MYSQL_TCP_PORT=3307
    networks:
      - nesttodo
networks:
  nesttodo:
